### PR TITLE
Theme typescript

### PR DESCRIPTION
**Pull request by danethurber**
Theme typescript

### CODE REVIEW

**Comment by jaketrent** [comment]
Really glad you're doing Theme.  I was making Badge strict, and it required the dependencies to be better typed.  This should help.

**Comment by EdwardIrby** [comment]
Getting some weird build errors when I run `yarn && yarn build` 

- I tried building theme separately but it still failed.
- I tried pulling in master too but no luck.


Screen Shot 2020-10-09 at 4 01 00 PM

**Review by EdwardIrby — APPROVED** [review]

**Review by EdwardIrby — CHANGES_REQUESTED** [review]
Getting some weird build errors when I run `yarn && yarn build` 

- I tried building theme separately but it still failed.
- I tried pulling in master too but no luck.


Screen Shot 2020-10-09 at 4 01 00 PM

**Review by EdwardIrby — APPROVED** [review]

**Comment by EdwardIrby** [comment]
> Getting some weird build errors when I run `yarn && yarn build`
> 
>     * I tried building theme separately but it still failed.
> 
>     * I tried pulling in master too but no luck.
> 
> 
> Screen Shot 2020-10-09 at 4 01 00 PM

Figured it out and fixed just some off typings

**Pull request merged**
