### PR TITLE
fix: linting errors cleanup

### LINKED ISSUE #733: Linting cleanup
Resolve linting errors in monorepo

Desired Behavior: when merging master and resolving conflicts or when running lint from root it is preferable to only be presented with linting errors from code one has touched.

### PR DESCRIPTION
**Pull request by EdwardIrby**
Resolves linting errors across monorepo.

- Ignores key requirement in site and storybook stories
- ignore entire packages-api directory. Should we convert this to typescript or vanilla JS?

closes #733
---

- `npm run bootstrap`
- `npm run lint`

### CODE REVIEW

**Comment by jaketrent** [comment]
@EdwardIrby , I get quite a bit of output from root `npm run lint`.  Should I be expecting this?

[output.txt](https://github.com/pluralsight/design-system/files/3970097/output.txt)

**Comment by EdwardIrby** [comment]
> @EdwardIrby , I get quite a bit of output from root `npm run lint`. Should I be expecting this?
> 
> [output.txt](https://github.com/pluralsight/design-system/files/3970097/output.txt)

The key messages yes as we had discussed making those a warning for site and storybook the others I must off missed. I'll go resolve those. I know all the errors are gone.

**Comment by danethurber** [comment]
@jaketrent i'm getting warnings but not errors. not sure why you have 7 errors

**Comment by jaketrent** [comment]
Hmmm, can't figure out why I'm getting them then, if others aren't.  Edward, will you confirm that you do/don't see what I'm seeing?

before:

```
✖ 393 problems (347 errors, 46 warnings)
  94 errors and 0 warnings potentially fixable with the `--fix` option.
```

after:

```
✖ 275 problems (7 errors, 268 warnings)
  7 errors and 0 warnings potentially fixable with the `--fix` option.
```

At least it's better! :D

**Comment by danethurber** [comment]
@EdwardIrby in the root level package.json file please remove the "lint:no-fail" script

 then in the `.travis.yml` file please update the lint step to use `npm run lint`

**Comment by EdwardIrby** [comment]
@jaketrent if we choose to ignore key inside stories and the site.

Then our warning are reduced down to this
```
> eslint .


/Users/edward/Workspace/design-system/packages/carousel/src/react/__specs__/index.spec.js
  131:5  warning  Skipped test  jest/no-disabled-tests
  132:5  warning  Skipped test  jest/no-disabled-tests
  136:5  warning  Skipped test  jest/no-disabled-tests
  140:5  warning  Skipped test  jest/no-disabled-tests
  144:5  warning  Skipped test  jest/no-disabled-tests
  148:5  warning  Skipped test  jest/no-disabled-tests

/Users/edward/Workspace/design-system/packages/carousel/src/react/index.js
  259:29  warning  React Hook React.useEffect has a spread element in its dependency array. This means we can't statically verify whether you've passed the correct dependencies  react-hooks/exhaustive-deps

/Users/edward/Workspace/design-system/packages/carousel/src/react/use-swipe.js
  51:3  warning  The 'handleStart' function makes the dependencies of useEffect Hook (at line 49) change on every render. Move it inside the useEffect callback. Alternatively, wrap the 'handleStart' definition into its own useCallback() Hook  react-hooks/exhaustive-deps
  63:3  warning  The 'handleEnd' function makes the dependencies of useEffect Hook (at line 49) change on every render. Move it inside the useEffect callback. Alternatively, wrap the 'handleEnd' definition into its own useCallback() Hook      react-hooks/exhaustive-deps

/Users/edward/Workspace/design-system/packages/link/src/react/index.js
  22:55  warning  Assignments to the 'tagName' variable from inside React Hook React.useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside React.useEffect  react-hooks/exhaustive-deps

✖ 10 problems (0 errors, 10 warnings)
```

**Comment by EdwardIrby** [comment]
> @EdwardIrby in the root level package.json file please remove the "lint:no-fail" script
> 
> then in the `.travis.yml` file please update the lint step to use `npm run lint`

Done!

**Comment by EdwardIrby** [comment]
> Hmmm, can't figure out why I'm getting them then, if others aren't. Edward, will you confirm that you do/don't see what I'm seeing?
> 
> before:
> 
> ```
> ✖ 393 problems (347 errors, 46 warnings)
>   94 errors and 0 warnings potentially fixable with the `--fix` option.
> ```
> 
> after:
> 
> ```
> ✖ 275 problems (7 errors, 268 warnings)
>   7 errors and 0 warnings potentially fixable with the `--fix` option.
> ```
> 
> At least it's better! :D

I'm not getting those 7 errors.  I think you need to run a build on emptystate as the *.dist.js files are generated.

**Pull request merged**
