### PR TITLE
[tab]: Update Tab.ListItem type to use ReactNode as children

### PR DESCRIPTION
**Pull request by willsoto**
By making it a string typescript was not allowing the following content:

```
My items (50)
```

where 50 is a `number`. By changing it to `React.ReactNode`, that case is fixed and we now match the standard `PropsWithChildren` type in React:

```typescript
type PropsWithChildren<P> = P & { children?: ReactNode };
```

**I do notice that the `PropTypes` for the `ListItem` only wants a `string` - can that be updated?**

https://github.com/pluralsight/design-system/blob/dcf5395bee91dc24cd03e74dbcd100d30fa8025e/packages/tab/src/react/list-item.js#L55

### CODE REVIEW

**Comment by willsoto** [comment]
One thing to note here is that the following will raise a proptypes error:

```tsx
const pendingAdditions = 10;

<Tab.List>
  <Tab.ListItem
    id="add"
    onClick={() => setActiveTab("add")}
    active={activeTab === "add"}
  >
    Content to be added ({pendingAdditions})
  </Tab.ListItem>
</Tab.List>
```

```
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `ForwardRef`, expected `string`.
    in ForwardRef (created by PendingChangesPage)
    in PendingChangesPage
    in Router (created by MemoryRouter)
    in MemoryRouter
    in ApolloProvider (created by MockedProvider)
    in MockedProvider

  107 |         <Box padding="lg" className="container mx-auto">
  108 |           <Tab.List>
> 109 |             <Tab.ListItem
      |             ^
  110 |               id="add"
  111 |               onClick={() => setActiveTab("add")}
  112 |               active={activeTab === "add"}>
```

**Comment by willsoto** [comment]
@jaketrent does that mean I am okay to change the `propTypes`?

**Comment by jaketrent** [comment]
@willsoto yes, please update the proptypes too, and we'll get it merged.

**Comment by willsoto** [comment]
@jaketrent - done

**Pull request merged**
