### PR TITLE
add page heading patterns to docs

### PR DESCRIPTION
**Pull request by jaketrent**
- Used frame labels in figma so that designers and developers are hopefully talking the same language.
- Called the last pattern in figma "Basic alternative". It was unlabeled in figma.
- Seems like some explanatory text would be useful. I see patterns without context. Oooh, I like this one, it has all the widgets I need. For instance, how would one decide which of the "basic" patterns he should use? One has an icon and fewer buttons, but that doesn't seem to indicate enough to be educated about the existence of 2 similar choices.

### CODE REVIEW

**Review by sweeting — COMMENTED** [review]
It might be better to call these Headers instead Headings, since we have a text component called Heading.

**Comment by jaketrent** [comment]
@sweeting "Header" is fine with me.  Would you like that applied to the side nav and url too, I suppose?

**Comment by sweeting** [comment]
@jaketrent Sorry for the delayed response, yes please.

**Comment by jaketrent** [comment]
@sweeting I made the "heading" -> "header" adjustment.

After thinking about it this morning, I think we should keep it as "heading", because "Page heading" patterns is exactly what it says.  We do have a Heading component.  These are common patterns os what it looks like to put those at page level. Calling these patterns "headers" introduces another word that has no precise meaning in our DS, leaving me more unsure on when to use what name to communicate clearly about these.

**Comment by sweeting** [comment]
@jaketrent I'm not concerned with adding a word (though similar) if it helps distinguish between two different. A "Heading" is a piece of text that helps create visual hierarchy. A "Header" is a collection of things at the top of a page or section. Let's not use the same word for things that have two different purposes. Also, the design for these patterns has always used the word "Header" and there is an html tag called `[<header>](https://html.com/tags/header/)` that is specifically intended for this purpose, which it might be good to use in the examples.

**Comment by jaketrent** [comment]
>  A "Heading" is a piece of text that helps create visual hierarchy. A "Header" is a collection of things at the top of a page or section. 

@sweeting sounds good.  Thank you for identifying the two things and how you see them.

**Review by danethurber — APPROVED** [review]
👍  good enough for me

**Pull request merged**
