### PR TITLE
fix(avatar): prevent css from being tree-shaken out

### PR DESCRIPTION
**Pull request by jaketrent**
From:
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

This means if you use something like css-loader in your project and
import a CSS file, it needs to be added to the side effect list so
it will not be unintentionally dropped in production mode

### CODE REVIEW

**Comment by jaketrent** [comment]
Confirmed locally that this fix also fixes the current styles issue on DS docs prod

Screen Shot 2021-06-24 at 11 56 38 AM

Local prod build:

Screen Shot 2021-06-24 at 11 57 23 AM

**Comment by jaketrent** [comment]
@danethurber since Edward is out, you're here, and the change is small and impactful, I wonder if you might not give this a second set of eyes?

**Review by danethurber — APPROVED** [review]
nice!

**Comment by danethurber** [comment]
do you need to do this to every project?

**Comment by jaketrent** [comment]
@danethurber yes, and we will. We have only converted Avatar atm.

**Pull request merged**
