### PR TITLE
new components: useListbox, Select, & Menu

### PR DESCRIPTION
**Pull request by EdwardIrby**
# Objective
Provide stateless components and reusable hooks to make implementing a simple pattern for custom Dropdowns easier for Pluralsight devs.
### Interfaces

```typescript
interface SelectedItem {
  id: React.ReactText
  name: React.ReactText
}

export interface UseListboxProps
  extends Omit<HTMLPropsFor<'button'>, 'onChange' | 'value'> {
  disabled?: boolean
  error?: boolean
  onChange?: (
    evt: React.MouseEvent | React.KeyboardEvent,
    value: SelectedItem
  ) => void
  onClick?: (e: React.MouseEvent | React.KeyboardEvent) => void
  placeholder?: string
  size?: ValueOf<typeof vars.sizes>
  'data-testid'?: string
  value?: SelectedItem
  labelId?: string
  mountOpen?: boolean
}
```

### Convenience Wrapper

**Placeholder setup**
```typescript
import Select from '@pluralsight/ps-design-system-select'
const items = [
  { id: 'One item', name: 'One item' },
  { id: 'Two item', name: 'Two item' },
  { id: 'Three item', name: 'Three item' }
]
return (
  <Select
      position={Select.positions.belowLeft}
      items={items}
      placeholder={'Select item'}
    />
)
```

**Default selected setup**
```typescript
import Select from '@pluralsight/ps-design-system-select'
const items = [
  { id: 'One item', name: 'One item' },
  { id: 'Two item', name: 'Two item' },
  { id: 'Three item', name: 'Three item' }
]
return (
  <Select
      position={Select.positions.belowRight}
      items={items}
      value={{
        name: items[1].name,
        id: items[1].id
      }}
  />
)
```

**custom menu items: static** (@KaidenR  this one's for you!)
```typescript
import Select from '@pluralsight/ps-design-system-select'
import Menu, {
  MenuItemWithDescription
} from '@pluralsight/ps-design-system-menu'
import { colorsStatus } from '@pluralsight/ps-design-system-core'

const itemsWithDescription = [
  {
    id: 'Can view',
    name: 'Can view',
    description: 'View details, content and other members in the channel.'
  },
  {
    id: 'Can edit',
    name: 'Can edit',
    description:
      'Edit details, add or remove content and invite or remove members'
  },
  {
    id: 'Make Owner',
    name: 'Make Owner',
    description:
      'Edit details, add or remove content, invite or remove members and delete Channel'
  }
]

return (
  <Select
        position={Select.positions.belowRight}
        value={{
          name: itemsWithDescription[0].name,
          id: itemsWithDescription[0].id
        }}
      >
        {itemsWithDescription.map(i => (
          <MenuItemWithDescription {...i} key={i.id} />
        ))}
        <Menu.Divider />
        <Menu.Item
          onClick={handleClick}
          style={{ color: colorsStatus.error }}
          value={{
            name: itemsWithDescription[0].name,
            id: itemsWithDescription[0].id
          }}
        >
          Remove Member
        </Menu.Item>
    </Select>
)
```

**custom menu items: dynamic** (doesn't support multiple menu item types unless you build an item to do so)
``` typescript
import Select from '@pluralsight/ps-design-system-select'
import { MenuItemWithDescription } from '@pluralsight/ps-design-system-menu'

const itemsWithDescription = [
  {
    id: 'Can view',
    name: 'Can view',
    description: 'View details, content and other members in the channel.'
  },
  {
    id: 'Can edit',
    name: 'Can edit',
    description:
      'Edit details, add or remove content and invite or remove members'
  },
  {
    id: 'Make Owner',
    name: 'Make Owner',
    description:
      'Edit details, add or remove content, invite or remove members and delete Channel'
  }
]

return (
    <Select
        items={itemsWithDescription}
        position={Select.positions.belowRight}
        renderOption={(MenuItemWithDescription as unknown) as React.FC}
        value={{
          name: itemsWithDescription[0].name,
          id: itemsWithDescription[0].id
        }}
    />
)
```

### Create a reusable Dropdown:
```typescript
import { useListbox, UseListboxProps, positions} from '@pluralsight/ps-design-system-select'
import * as PositionComponents from '@pluralsight/ps-design-system-position'
import Menu from '@pluralsight/ps-design-system-menu'
import {
  ValueOf,
  ForwardRefComponent
} from '@pluralsight/ps-design-system-util'

interface DropdownProps extends UseListboxProps {
  position: ValueOf<typeof positions>
  items: Array<{ id: React.ReactText; name: React.ReactText }>
}
const Dropdown = forwardRef((props, ref) => {
  const {
    items = [],
    position = 'belowLeft',
    children,
    ...rest
  } = props
  const { buttonProps, selectedProps, menuProps, isOpen } = useListbox(
    rest,
    ref
  )
  return (
    <PositionComponents.Position
      position={PositionComponents[position]}
      when={isOpen}
      show={
        <Menu origin={Menu.origins.topLeft} {...menuProps}>
          {items.map(i => (
            <Menu.Item value={i} key={i.value}>
              {i.name}
              <Menu.Check />
             </Menu.Item>)
            }
        </Menu>
      }
    >
      <Button {...buttonProps}>
        <Selected {...selectedProps} />
      </Button>
    </PositionComponents.Position>
  )
}) as ForwardRefComponent<'button', DropdownProps>
```
**Note:** 
- You can pass whatever you want as a child to `Menu.Item`. You just must ensure the `value` prop on `Menu.Item` adheres to the `SelectedItem` interface.  where the `selectedItem.value` is unique
- `closeMenu` callback will focus `Select.Button` on global events (resize, scroll, click outside menu)
  - Should we do this?
### Use custom dropdown
```typescript

const items = [
  { value: 'One item', option: 'One item' },
  { value: 'Two item', option: 'Two item' },
  { value: 'Three item', option: 'Three item' }
]

// placeholder example
 <Dropdown options={items} placeholder={'Select item'} />
 
// initial value selected example
 <Dropdown
      options={items}
      value={{
        option: items[1].option,
        value: items[1].value
      }}
    />
```

### CODE REVIEW

**Review by danethurber — COMMENTED** [review]
some initial thoughts quickly looking over the code. i'll find some time to dig in deeper later(or better yet we could have a team code review 🤔 )

- i like the seperation between the hooks and components
- i'm glad the polymorphic stuff worked well 🥳 
  - i'd probably name the polymorphic interface differently. `ForwardRefComponent` doesn't mention anything about polymorphism
- the examples of building a dropdown look simple 💥 
  - I assume we'd replace the current Dropdown in time
- naming wise maybe we can make things more understandable
  - Select isn't a full select component. maybe SelectPrimitive idk
  - or maybe there is Select for the atoms and SelectField for the Select+Field combo 🤷 
- interested in your take on the pros/cons of rolling our own `useSelect` vs the `useSelect` hook from downshiftjs.
  - should we drop downshift all together?
  - should we keep downshift for somethings but not for select/dropdown
  - does downshift still have merit but we need to compare/contrast these two useSelect approaches
- Menu component is simple and I see many places we could use it
- i'd love to decide on a strategy of naming/exports/organization for what's a building block vs a logic headless hook vs convenience wrappers
  - this pr might be a good candidate to decide that
  - we can update other components to match in time
  - maybe Select.Button is actually FormButton/ActivatorButton/Field.Button and useSelect is decoupled in a separate package 🤷‍♂️

**Comment by EdwardIrby** [comment]
> some initial thoughts quickly looking over the code. i'll find some time to dig in deeper later(or better yet we could have a team code review 🤔 )
> 
> * i like the seperation between the hooks and components
> * i'm glad the polymorphic stuff worked well 🥳
>   
>   * i'd probably name the polymorphic interface differently. `ForwardRefComponent` doesn't mention anything about polymorphism
> * the examples of building a dropdown look simple 💥
>   
>   * I assume we'd replace the current Dropdown in time
> * naming wise maybe we can make things more understandable
>   
>   * Select isn't a full select component. maybe SelectPrimitive idk
>   * or maybe there is Select for the atoms and SelectField for the Select+Field combo 🤷
> * interested in your take on the pros/cons of rolling our own `useSelect` vs the `useSelect` hook from downshiftjs.
>   
>   * should we drop downshift all together?
>   * should we keep downshift for somethings but not for select/dropdown
>   * does downshift still have merit but we need to compare/contrast these two useSelect approaches
> * Menu component is simple and I see many places we could use it
> * i'd love to decide on a strategy of naming/exports/organization for what's a building block vs a logic headless hook vs convenience wrappers
>   
>   * this pr might be a good candidate to decide that
>   * we can update other components to match in time
>   * maybe Select.Button is actually FormButton/ActivatorButton/Field.Button and useSelect is decoupled in a separate package 🤷‍♂️

I'm down for a team review. I think it'll help with the questions/points you pose.

**Comment by EdwardIrby** [comment]
@danethurber getting the last bits done made splitting this hard. I think we can just wait until we go to a single package. I'm going to leave listbox in Select for now.

**Review by danethurber — APPROVED** [review]
LGTM 👍

**Pull request merged**
